In [1]:
import numpy as np

arr = np.array([10, 20, 30])
print(arr)

arr0 = np.zeros(5)
arr1 = np.ones(5)
print(arr0)
print(arr1)

[10 20 30]
[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]


In [14]:
arr1 = np.arange(0,100,20)
arr2 = np.linspace(0,100,5)
